### ISSUE TITLE
Update dependencies & fix test import `page-object`

### ISSUE THREAD

**Issue by mkszepp** [lolmaus/ember-drag-sort#76]
`ember-drag-sort@3.0.0` has problems with the latest `embroider@1.4` version (https://github.com/embroider-build/embroider/issues/1153)

There is necessary to fix the imports in `test-support` folder. I think there were forgot, because other files are alreay correct

https://github.com/kaliber5/ember-drag-sort/blob/56399dbef78dceb3ee6cbce80684a833c8ccb2ef/test-support/pages/components/_component.js#L1-L6

https://github.com/kaliber5/ember-drag-sort/blob/56399dbef78dceb3ee6cbce80684a833c8ccb2ef/test-support/pages/components/drag-sort-item.js#L1-L4

**Comment by rwwagner90** [comment]
@simonihmig @lolmaus I just hit this as well. Any chance the PR can be merged?

**Comment by basz** [comment]
yes please.

**Comment by lolmaus** [comment]
Fixed in #75.
